import { Inter } from "next/font/google";
import "./globals.css";
import Layout from '@/app/site/components/appLayout/layout.jsx';
import { Suspense } from "react";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "IMScience",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Suspense>
        <Layout>{children}</Layout>
        </Suspense>
      </body>
    </html>
  );
}
