import { Inter } from "next/font/google";
import './globals.css'
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "IMScience Admin",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <div className="flex flex-1">
      <main className="flex-1 bg-white">
        {children}
      </main>
    </div>
  );
}